---
title: "04_3-Caderno-InfEst-parte6"
author: "Helena R. S. D'Espindula"
output:
  html_document: 
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
      number_sections: true
  pdf_document:
date: "2024-04-27"
---

```{r setup, echo=TRUE, include=TRUE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE, warning = TRUE, error = TRUE)
library(ggplot2)
```
\usepackage{amsmath}

```{r eval=FALSE, include=TRUE}
# Vari치veis Aleat칩rias e Distribui칞칫es de Probabilidade


## Vari치veis aleat칩rias


### Defini칞칚o
- Vari치vel aleat칩ria: Descri칞칚o num칠rica do resultado de um experimento aleat칩rio.
- Nota칞칚o: 洧녧 denota a vari치vel aleat칩ria, enquanto 洧녽 denota os valores realizados de uma vari치vel aleat칩ria.


### Exemplo: Lan칞amento de duas moedas
Lan칞amento de duas moedas honestas e defina $Y =$ n칰mero de resultados cara $(C)$.

[[]]
Figura 2. Vari치vel aleat칩ria definida sobre pontos do espa칞o amostral
```

## Exercicios de Metodos Numericos

http://shiny.leg.ufpr.br/wagner/MetodosNumericos/



```{r}
# Y ~ Normal(mu, sigma).
y <- 1; mu <- 100; sigma <- 100
# f(y; mu, sigma).
dnorm(y, mean = mu, sd = sigma)
## [1] 0.02419707
# exp(-(y - mu)^2/(2 * sigma^2))/sqrt(2 * pi * sigma^2)
# F(y; mu, sigma).
pnorm(y, mean = mu, sd = sigma)
## [1] 0.8413447
# Quantil.
q <- 0.25
y_q <- qnorm(q, mean = mu, sd = sigma); y_q
## [1] 173.2551
```



