---
title: "Processamento_BD--2024-08-24"
author: "Helena"
date: "2024-08-24"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
      number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



# Dia 24-08-2024

## Combinando - Municipios e Estados

### Produto cartesiano

```{bash eval=FALSE, include=TRUE}

hrsdespindula@h9:~/DSBD/07-Processamento_de_Big_Data$ sqlite3 dsbd.db
sqlite> .read estados.sql
sqlite> .read municipios.sql

sqlite> SELECT * FROM municipio;
[...]
5221007|Taquaral de Goiás|GO
5221080|Teresina de Goiás|GO
5221197|Terezópolis de Goiás|GO
5221304|Três Ranchos|GO
5221403|Trindade|GO
5221452|Trombas|GO
5221502|Turvânia|GO
5221551|Turvelândia|GO
5221577|Uirapuru|GO
5221601|Uruaçu|GO
5221700|Uruana|GO
5221809|Urutaí|GO
5221858|Valparaíso de Goiás|GO
5221908|Varjão|GO
5222005|Vianópolis|GO
5222054|Vicentinópolis|GO
5222203|Vila Boa|GO
5222302|Vila Propício|GO
5300108|Brasília|DF

sqlite> SELECT * FROM municipio, estado; ## Combine cada tupla de município com TODAS possibilidades de estado
[...]
5300108|Brasília|DF|AC|Acre
5300108|Brasília|DF|AL|Alagoas
5300108|Brasília|DF|AP|Amapá
5300108|Brasília|DF|AM|Amazonas
5300108|Brasília|DF|BA|Bahia
5300108|Brasília|DF|CE|Ceará
5300108|Brasília|DF|DF|Distrito Federal
5300108|Brasília|DF|ES|Espírito Santo
5300108|Brasília|DF|GO|Goiás
5300108|Brasília|DF|MA|Maranhão
5300108|Brasília|DF|MT|Mato Grosso
5300108|Brasília|DF|MS|Mato Grosso do Sul
5300108|Brasília|DF|MG|Minas Gerais
5300108|Brasília|DF|PA|Pará
5300108|Brasília|DF|PB|Paraíba
5300108|Brasília|DF|PR|Paraná
5300108|Brasília|DF|PE|Pernambuco
5300108|Brasília|DF|PI|Piauí
5300108|Brasília|DF|RJ|Rio de Janeiro
5300108|Brasília|DF|RN|Rio Grande do Norte
5300108|Brasília|DF|RS|Rio Grande do Sul
5300108|Brasília|DF|RO|Rondônia
5300108|Brasília|DF|RR|Roraima
5300108|Brasília|DF|SC|Santa Catarina
5300108|Brasília|DF|SP|São Paulo
5300108|Brasília|DF|SE|Sergipe
5300108|Brasília|DF|TO|Tocantins

sqlite> SELECT COUNT(*) FROM estado;
COUNT(*)
27

sqlite> SELECT COUNT(*) FROM municipio;
COUNT(*)
5570

sqlite> SELECT COUNT(*) FROM municipio, estado; ## estados x municipios = 27 x 5570
COUNT(*)
150390

sqlite> SELECT * FROM municipio,estado order by nome;
[...]
1505106|Óbidos|PA|TO|Tocantins
3533809|Óleo|SP|AC|Acre
3533809|Óleo|SP|AL|Alagoas
3533809|Óleo|SP|AP|Amapá
3533809|Óleo|SP|AM|Amazonas
3533809|Óleo|SP|BA|Bahia
3533809|Óleo|SP|CE|Ceará
3533809|Óleo|SP|DF|Distrito Federal
3533809|Óleo|SP|ES|Espírito Santo
3533809|Óleo|SP|GO|Goiás
3533809|Óleo|SP|MA|Maranhão
3533809|Óleo|SP|MT|Mato Grosso
3533809|Óleo|SP|MS|Mato Grosso do Sul
3533809|Óleo|SP|MG|Minas Gerais
3533809|Óleo|SP|PA|Pará
3533809|Óleo|SP|PB|Paraíba
3533809|Óleo|SP|PR|Paraná
3533809|Óleo|SP|PE|Pernambuco
3533809|Óleo|SP|PI|Piauí
3533809|Óleo|SP|RJ|Rio de Janeiro
3533809|Óleo|SP|RN|Rio Grande do Norte
3533809|Óleo|SP|RS|Rio Grande do Sul
3533809|Óleo|SP|RO|Rondônia
3533809|Óleo|SP|RR|Roraima
3533809|Óleo|SP|SC|Santa Catarina
3533809|Óleo|SP|SP|São Paulo
3533809|Óleo|SP|SE|Sergipe
3533809|Óleo|SP|TO|Tocantins

sqlite> SELECT * FROM municipio t1, estado t2 ORDER BY t2.nome;
5221007|Taquaral de Goiás|GO|TO|Tocantins
5221080|Teresina de Goiás|GO|TO|Tocantins
5221197|Terezópolis de Goiás|GO|TO|Tocantins
5221304|Três Ranchos|GO|TO|Tocantins
5221403|Trindade|GO|TO|Tocantins
5221452|Trombas|GO|TO|Tocantins
5221502|Turvânia|GO|TO|Tocantins
5221551|Turvelândia|GO|TO|Tocantins
5221577|Uirapuru|GO|TO|Tocantins
5221601|Uruaçu|GO|TO|Tocantins
5221700|Uruana|GO|TO|Tocantins
5221809|Urutaí|GO|TO|Tocantins
5221858|Valparaíso de Goiás|GO|TO|Tocantins
5221908|Varjão|GO|TO|Tocantins
5222005|Vianópolis|GO|TO|Tocantins
5222054|Vicentinópolis|GO|TO|Tocantins
5222203|Vila Boa|GO|TO|Tocantins
5222302|Vila Propício|GO|TO|Tocantins
5300108|Brasília|DF|TO|Tocantins

sqlite> SELECT * FROM municipio t1, estado t2 ORDER BY t2.nome LIMIT 10;
## ALIAS: municipio AS t1, estado AS t2
codigo|nome|uf|uf|nome
1100015|Alta Floresta DOeste|RO|AC|Acre
1100023|Ariquemes|RO|AC|Acre
1100031|Cabixi|RO|AC|Acre
1100049|Cacoal|RO|AC|Acre
1100056|Cerejeiras|RO|AC|Acre
1100064|Colorado do Oeste|RO|AC|Acre
1100072|Corumbiara|RO|AC|Acre
1100080|Costa Marques|RO|AC|Acre
1100098|Espigão DOeste|RO|AC|Acre
1100106|Guajará-Mirim|RO|AC|Acre

sqlite> SELECT * FROM municipio t1, estado t2 WHERE t1.uf = t2.uf ORDER BY t1.nome;
## Combine as informações de cada município com o estado, mas somente quando a uf do município for igual a uf na tabela estado.
[...]
2600401|Água Preta|PE|PE|Pernambuco
4300059|Água Santa|RS|RS|Rio Grande do Sul
2600500|Águas Belas|PE|PE|Pernambuco
3100906|Águas Formosas|MG|MG|Minas Gerais
4200556|Águas Frias|SC|SC|Santa Catarina
5200258|Águas Lindas de Goiás|GO|GO|Goiás
4200606|Águas Mornas|SC|SC|Santa Catarina
3101003|Águas Vermelhas|MG|MG|Minas Gerais
3500402|Águas da Prata|SP|SP|São Paulo
4200507|Águas de Chapecó|SC|SC|Santa Catarina
3500501|Águas de Lindóia|SP|SP|São Paulo
3500550|Águas de Santa Bárbara|SP|SP|São Paulo
3500600|Águas de São Pedro|SP|SP|São Paulo
3200136|Águia Branca|ES|ES|Espírito Santo
3501202|Álvares Florence|SP|SP|São Paulo
3501301|Álvares Machado|SP|SP|São Paulo
3501400|Álvaro de Carvalho|SP|SP|São Paulo
4301552|Áurea|RS|RS|Rio Grande do Sul
4101150|Ângulo|PR|PR|Paraná
2900504|Érico Cardoso|BA|BA|Bahia
1505106|Óbidos|PA|PA|Pará
3533809|Óleo|SP|SP|São Paulo

sqlite> SELECT COUNT(*) FROM municipio t1, estado t2 WHERE t1.uf = t2.uf ORDER BY t1.nome;
COUNT(*)
5570

sqlite> SELECT * FROM municipio t1, estado t2 WHERE t1.uf = t2.uf ORDER BY t1.nome LIMIT 10;
codigo|nome|uf|uf|nome
5200050|Abadia de Goiás|GO|GO|Goiás
3100104|Abadia dos Dourados|MG|MG|Minas Gerais
5200100|Abadiânia|GO|GO|Goiás
1500107|Abaetetuba|PA|PA|Pará
3100203|Abaeté|MG|MG|Minas Gerais
2300101|Abaiara|CE|CE|Ceará
2900207|Abaré|BA|BA|Bahia
4100103|Abatiá|PR|PR|Paraná
2900108|Abaíra|BA|BA|Bahia
4200051|Abdon Batista|SC|SC|Santa Catarina

sqlite> SELECT * FROM municipio t1 WHERE t1.nome = t1.nome ORDER BY t1.nome LIMIT 10; ## ERRADO
codigo|nome|uf
5200050|Abadia de Goiás|GO
3100104|Abadia dos Dourados|MG
5200100|Abadiânia|GO
1500107|Abaetetuba|PA
3100203|Abaeté|MG
2300101|Abaiara|CE
2900207|Abaré|BA
4100103|Abatiá|PR
2900108|Abaíra|BA
4200051|Abdon Batista|SC
```


```{bash eval=FALSE, include=TRUE}
sqlite> SELECT nome, COUNT(*) FROM municipio GROUP BY nome HAVING COUNT(*)>1 LIMIT 10; ## Fonte da internet <https://www.geeksforgeeks.org/sql-query-to-find-duplicate-names-in-a-table/>
nome|COUNT(*)
Alagoinha|2
Alto Alegre|3
Alto Paraíso|2
Alvorada|2
Amparo|2
Anchieta|2
Antônio Carlos|2
Aparecida|2
Araguanã|2
Araruna|2

sqlite> SELECT nome, COUNT(*) AS Repeticoes FROM municipio GROUP BY nome HAVING COUNT(*)>1 LIMIT 10;
nome|Repeticoes
Alagoinha|2
Alto Alegre|3
Alto Paraíso|2
Alvorada|2
Amparo|2
Anchieta|2
Antônio Carlos|2
Aparecida|2
Araguanã|2
Araruna|2
```


```{bash eval=FALSE, include=TRUE}
sqlite> SELECT * FROM municipio t1, municipio t2 ORDER BY t1.nome LIMIT 10;
codigo|nome|uf|codigo|nome|uf
5200050|Abadia de Goiás|GO|1100015|Alta Floresta DOeste|RO
5200050|Abadia de Goiás|GO|1100023|Ariquemes|RO
5200050|Abadia de Goiás|GO|1100031|Cabixi|RO
5200050|Abadia de Goiás|GO|1100049|Cacoal|RO
5200050|Abadia de Goiás|GO|1100056|Cerejeiras|RO
5200050|Abadia de Goiás|GO|1100064|Colorado do Oeste|RO
5200050|Abadia de Goiás|GO|1100072|Corumbiara|RO
5200050|Abadia de Goiás|GO|1100080|Costa Marques|RO
5200050|Abadia de Goiás|GO|1100098|Espigão DOeste|RO
5200050|Abadia de Goiás|GO|1100106|Guajará-Mirim|RO

sqlite> SELECT * FROM municipio t1, municipio t2 WHERE t1.nome = t2.nome ORDER BY t1.nome LIMIT 30;
codigo|nome|uf|codigo|nome|uf
5200050|Abadia de Goiás|GO|5200050|Abadia de Goiás|GO
3100104|Abadia dos Dourados|MG|3100104|Abadia dos Dourados|MG
5200100|Abadiânia|GO|5200100|Abadiânia|GO
1500107|Abaetetuba|PA|1500107|Abaetetuba|PA
3100203|Abaeté|MG|3100203|Abaeté|MG
2300101|Abaiara|CE|2300101|Abaiara|CE
2900207|Abaré|BA|2900207|Abaré|BA
4100103|Abatiá|PR|4100103|Abatiá|PR
2900108|Abaíra|BA|2900108|Abaíra|BA
4200051|Abdon Batista|SC|4200051|Abdon Batista|SC
1500131|Abel Figueiredo|PA|1500131|Abel Figueiredo|PA
4200101|Abelardo Luz|SC|4200101|Abelardo Luz|SC
3100302|Abre Campo|MG|3100302|Abre Campo|MG
2600054|Abreu e Lima|PE|2600054|Abreu e Lima|PE
1700251|Abreulândia|TO|1700251|Abreulândia|TO
3100401|Acaiaca|MG|3100401|Acaiaca|MG
2900306|Acajutiba|BA|2900306|Acajutiba|BA
2300150|Acarape|CE|2300150|Acarape|CE
2300200|Acaraú|CE|2300200|Acaraú|CE
2400109|Acari|RN|2400109|Acari|RN
1500206|Acará|PA|1500206|Acará|PA
2200053|Acauã|PI|2200053|Acauã|PI
4300034|Aceguá|RS|4300034|Aceguá|RS
2300309|Acopiara|CE|2300309|Acopiara|CE
5100102|Acorizal|MT|5100102|Acorizal|MT
1200013|Acrelândia|AC|1200013|Acrelândia|AC
5200134|Acreúna|GO|5200134|Acreúna|GO
3500105|Adamantina|SP|3500105|Adamantina|SP
5200159|Adelândia|GO|5200159|Adelândia|GO
3500204|Adolfo|SP|3500204|Adolfo|SP

sqlite> SELECT * FROM municipio t1, municipio t2 WHERE t1.nome = t2.nome and t1.codigo <> t2.codigo ORDER BY t1.nome LIMIT 30;
codigo|nome|uf|codigo|nome|uf
2500502|Alagoinha|PB|2600609|Alagoinha|PE
2600609|Alagoinha|PE|2500502|Alagoinha|PB
1400050|Alto Alegre|RR|3501103|Alto Alegre|SP
1400050|Alto Alegre|RR|4300554|Alto Alegre|RS
3501103|Alto Alegre|SP|1400050|Alto Alegre|RR
3501103|Alto Alegre|SP|4300554|Alto Alegre|RS
4300554|Alto Alegre|RS|1400050|Alto Alegre|RR
4300554|Alto Alegre|RS|3501103|Alto Alegre|SP
1100403|Alto Paraíso|RO|4128625|Alto Paraíso|PR
4128625|Alto Paraíso|PR|1100403|Alto Paraíso|RO
1700707|Alvorada|TO|4300604|Alvorada|RS
4300604|Alvorada|RS|1700707|Alvorada|TO
2500734|Amparo|PB|3501905|Amparo|SP
3501905|Amparo|SP|2500734|Amparo|PB
3200409|Anchieta|ES|4200804|Anchieta|SC
4200804|Anchieta|SC|3200409|Anchieta|ES
3102902|Antônio Carlos|MG|4201208|Antônio Carlos|SC
4201208|Antônio Carlos|SC|3102902|Antônio Carlos|MG
2500775|Aparecida|PB|3502507|Aparecida|SP
3502507|Aparecida|SP|2500775|Aparecida|PB
1702158|Araguanã|TO|2100873|Araguanã|MA
2100873|Araguanã|MA|1702158|Araguanã|TO
2501005|Araruna|PB|4101705|Araruna|PR
4101705|Araruna|PR|2501005|Araruna|PB
2401107|Areia Branca|RN|2800506|Areia Branca|SE
2800506|Areia Branca|SE|2401107|Areia Branca|RN
2700409|Atalaia|AL|4102208|Atalaia|PR
4102208|Atalaia|PR|2700409|Atalaia|AL
2301703|Aurora|CE|4201901|Aurora|SC
4201901|Aurora|SC|2301703|Aurora|CE

sqlite> SELECT * FROM municipio t1, municipio t2 WHERE t1.nome = t2.nome and t1.codigo < t2.codigo ORDER BY t1.nome LIMIT 30;
codigo|nome|uf|codigo|nome|uf
2500502|Alagoinha|PB|2600609|Alagoinha|PE
1400050|Alto Alegre|RR|3501103|Alto Alegre|SP
1400050|Alto Alegre|RR|4300554|Alto Alegre|RS
3501103|Alto Alegre|SP|4300554|Alto Alegre|RS
1100403|Alto Paraíso|RO|4128625|Alto Paraíso|PR
1700707|Alvorada|TO|4300604|Alvorada|RS
2500734|Amparo|PB|3501905|Amparo|SP
3200409|Anchieta|ES|4200804|Anchieta|SC
3102902|Antônio Carlos|MG|4201208|Antônio Carlos|SC
2500775|Aparecida|PB|3502507|Aparecida|SP
1702158|Araguanã|TO|2100873|Araguanã|MA
2501005|Araruna|PB|4101705|Araruna|PR
2401107|Areia Branca|RN|2800506|Areia Branca|SE
2700409|Atalaia|AL|4102208|Atalaia|PR
2301703|Aurora|CE|4201901|Aurora|SC
4102406|Bandeirantes|PR|5001508|Bandeirantes|MS
2401453|Baraúna|RN|2501534|Baraúna|PB
3505302|Barra Bonita|SP|4202099|Barra Bonita|SC
2501708|Barra de São Miguel|PB|2700607|Barra de São Miguel|AL
4102604|Barracão|PR|4301800|Barracão|RS
2903235|Barro Alto|BA|5203203|Barro Alto|GO
2201507|Batalha|PI|2700706|Batalha|AL
2903409|Belmonte|BA|4202156|Belmonte|SC
1501402|Belém|PA|2501906|Belém|PB
1501402|Belém|PA|2700805|Belém|AL
2501906|Belém|PB|2700805|Belém|AL
3107109|Boa Esperança|MG|3201001|Boa Esperança|ES
3107109|Boa Esperança|MG|4103008|Boa Esperança|PR
3201001|Boa Esperança|ES|4103008|Boa Esperança|PR
1400100|Boa Vista|RR|2502151|Boa Vista|PB

sqlite> SELECT COUNT(*) FROM municipio t1, municipio t2 WHERE t1.nome = t2.nome and t1.codigo < t2.codigo ORDER BY t1.nome LIMIT 30;
COUNT(*)
326

sqlite> SELECT * FROM municipio t1, municipio t2 WHERE t1.nome = t2.nome and t1.codigo < t2.codigo AND t1.uf = t2.uf ORDER BY t1.nome LIMIT 30;
[VAZIO]

sqlite> SELECT COUNT(*) FROM municipio t1, municipio t2 WHERE t1.nome = t2.nome and t1.codigo < t2.codigo AND t1.uf = t2.uf ORDER BY t1.nome LIMIT 30;
COUNT(*)
0

sqlite> SELECT * FROM municipio t1, municipio t2 WHERE t1.nome = t2.nome and t1.codigo < t2.codigo AND t1.uf <> t2.uf ORDER BY t1.nome LIMIT 30;
codigo|nome|uf|codigo|nome|uf
2500502|Alagoinha|PB|2600609|Alagoinha|PE
1400050|Alto Alegre|RR|3501103|Alto Alegre|SP
1400050|Alto Alegre|RR|4300554|Alto Alegre|RS
3501103|Alto Alegre|SP|4300554|Alto Alegre|RS
1100403|Alto Paraíso|RO|4128625|Alto Paraíso|PR
1700707|Alvorada|TO|4300604|Alvorada|RS
2500734|Amparo|PB|3501905|Amparo|SP
3200409|Anchieta|ES|4200804|Anchieta|SC
3102902|Antônio Carlos|MG|4201208|Antônio Carlos|SC
2500775|Aparecida|PB|3502507|Aparecida|SP
1702158|Araguanã|TO|2100873|Araguanã|MA
2501005|Araruna|PB|4101705|Araruna|PR
2401107|Areia Branca|RN|2800506|Areia Branca|SE
2700409|Atalaia|AL|4102208|Atalaia|PR
2301703|Aurora|CE|4201901|Aurora|SC
4102406|Bandeirantes|PR|5001508|Bandeirantes|MS
2401453|Baraúna|RN|2501534|Baraúna|PB
3505302|Barra Bonita|SP|4202099|Barra Bonita|SC
2501708|Barra de São Miguel|PB|2700607|Barra de São Miguel|AL
4102604|Barracão|PR|4301800|Barracão|RS
2903235|Barro Alto|BA|5203203|Barro Alto|GO
2201507|Batalha|PI|2700706|Batalha|AL
2903409|Belmonte|BA|4202156|Belmonte|SC
1501402|Belém|PA|2501906|Belém|PB
1501402|Belém|PA|2700805|Belém|AL
2501906|Belém|PB|2700805|Belém|AL
3107109|Boa Esperança|MG|3201001|Boa Esperança|ES
3107109|Boa Esperança|MG|4103008|Boa Esperança|PR
3201001|Boa Esperança|ES|4103008|Boa Esperança|PR
1400100|Boa Vista|RR|2502151|Boa Vista|PB

sqlite> SELECT COUNT(*) FROM municipio t1, municipio t2 WHERE t1.nome = t2.nome and t1.codigo < t2.codigo AND t1.uf <> t2.uf ORDER BY t1.nome LIMIT 30;
COUNT(*)
326
```

### Inner Join

Quando desejamos mostrar os dados de uma tabela , combinando os resultados com uma segunda através de sua chave estrangeira, estamos interessados em um INNER JOIN.

Combine o resultado da tabela A, somente quando encontrar um resultado relacionado na tabela B, onde a relação é definida pela chave estrangeira.

Sempre que fizer sentido, prefira usar Inner Joins no lugar de produtos cartesianos. Deixar a consulta mais clara.

```{bash eval=FALSE, include=TRUE}
## SELECT colunas FROM tabela1 INNER JOIN tabela2 ON tabela1.coluna = tabela2.coluna;

sqlite> SELECT * FROM municipio INNER JOIN estado ON municipio.uf = estado.uf LIMIT 20; 
## No Inner Join, use ON para indicar com oa relação entre as tabelas é definida.
codigo|nome|uf|uf|nome
1100015|Alta Floresta DOeste|RO|RO|Rondônia
1100023|Ariquemes|RO|RO|Rondônia
1100031|Cabixi|RO|RO|Rondônia
1100049|Cacoal|RO|RO|Rondônia
1100056|Cerejeiras|RO|RO|Rondônia
1100064|Colorado do Oeste|RO|RO|Rondônia
1100072|Corumbiara|RO|RO|Rondônia
1100080|Costa Marques|RO|RO|Rondônia
1100098|Espigão DOeste|RO|RO|Rondônia
1100106|Guajará-Mirim|RO|RO|Rondônia
1100114|Jaru|RO|RO|Rondônia
1100122|Ji-Paraná|RO|RO|Rondônia
1100130|Machadinho DOeste|RO|RO|Rondônia
1100148|Nova Brasilândia DOeste|RO|RO|Rondônia
1100155|Ouro Preto do Oeste|RO|RO|Rondônia
1100189|Pimenta Bueno|RO|RO|Rondônia
1100205|Porto Velho|RO|RO|Rondônia
1100254|Presidente Médici|RO|RO|Rondônia
1100262|Rio Crespo|RO|RO|Rondônia
1100288|Rolim de Moura|RO|RO|Rondônia

sqlite> SELECT * FROM municipio INNER JOIN estado ON municipio.uf = estado.uf ORDER by municipio.nome LIMIT 20;
## No Inner Join, use ON para indicar com oa relação entre as tabelas é definida.
codigo|nome|uf|uf|nome
5200050|Abadia de Goiás|GO|GO|Goiás
3100104|Abadia dos Dourados|MG|MG|Minas Gerais
5200100|Abadiânia|GO|GO|Goiás
1500107|Abaetetuba|PA|PA|Pará
3100203|Abaeté|MG|MG|Minas Gerais
2300101|Abaiara|CE|CE|Ceará
2900207|Abaré|BA|BA|Bahia
4100103|Abatiá|PR|PR|Paraná
2900108|Abaíra|BA|BA|Bahia
4200051|Abdon Batista|SC|SC|Santa Catarina
1500131|Abel Figueiredo|PA|PA|Pará
4200101|Abelardo Luz|SC|SC|Santa Catarina
3100302|Abre Campo|MG|MG|Minas Gerais
2600054|Abreu e Lima|PE|PE|Pernambuco
1700251|Abreulândia|TO|TO|Tocantins
3100401|Acaiaca|MG|MG|Minas Gerais
2900306|Acajutiba|BA|BA|Bahia
2300150|Acarape|CE|CE|Ceará
2300200|Acaraú|CE|CE|Ceará
2400109|Acari|RN|RN|Rio Grande do Norte

```

### Distinct

Quando não desejamos resultados duplicados, podemos usar a cláusula DISTINCT na consulta.
Formato:
`{bash}SELECT DISTINCT coluna1, coluna2, … FROM nomeTabela`;
A combinação de coluna1,coluna2,... nunca vai se repetir na resposta.
Quando uma duplicata é encontrada, o banco suprime da resposta.

```{bash eval=FALSE, include=TRUE}
sqlite> SELECT DISTINCT nome FROM municipio ORDER BY nome LIMIT 20;
nome
Abadia de Goiás
Abadia dos Dourados
Abadiânia
Abaetetuba
Abaeté
Abaiara
Abaré
Abatiá
Abaíra
Abdon Batista
Abel Figueiredo
Abelardo Luz
Abre Campo
Abreu e Lima
Abreulândia
Acaiaca
Acajutiba
Acarape
Acaraú
Acari

sqlite> SELECT DISTINCT nome, uf FROM municipio ORDER BY nome LIMIT 20;
nome|uf
Abadia de Goiás|GO
Abadia dos Dourados|MG
Abadiânia|GO
Abaetetuba|PA
Abaeté|MG
Abaiara|CE
Abaré|BA
Abatiá|PR
Abaíra|BA
Abdon Batista|SC
Abel Figueiredo|PA
Abelardo Luz|SC
Abre Campo|MG
Abreu e Lima|PE
Abreulândia|TO
Acaiaca|MG
Acajutiba|BA
Acarape|CE
Acaraú|CE
Acari|RN

sqlite> SELECT COUNT(*) FROM(SELECT DISTINCT nome, uf FROM municipio);
COUNT(*)
5570

sqlite> WITH tab1 as (SELECT DISTINCT nome, uf FROM municipio) SELECT COUNT(*) FROM tab1;
COUNT(*)
5570
```


## Exercícios

1. Crie uma tabela região, que conterá as cinco regiões do Brasil.
  a. Na tabela use como chave primária a sigla da região. Por exemplo, Nordeste é NE.
2. Modifique a tabela estados para que ela tenha uma ligação Nx1 entre estado e região.
  a. Não esqueça das restrições de integridade (ex.: chave estrangeira).
3. Faça as seguintes consultas:
  a. Exiba todos os municípios em ordem alfabética, juntamente com seus estados e regiões. Use inner join.
  b. Exiba todos os municípios homônimos, onde os homônimos devem estar na mesma região.
  c. Exiba todas as combinações únicas entre nomes de município e região do Brasil.
  d. Conte quantos municípios existem na região SUL do Brasil.
  e. Liste os municípios possuem ‘ão’ em algum lugar do nome, e que ficam no Nordeste.
4. Faça o Diagrama Físico do banco de dados modelado até o momento no DIA ou no Oracle SQL Datamod

### 1) Arquivo regioes.sql

```{sql eval=FALSE, include=TRUE}
DROP TABLE IF EXISTS municipio;
DROP TABLE IF EXISTS estado;
DROP TABLE IF EXISTS regiao;

CREATE TABLE regiao (
  sigla INT PRIMARY KEY,
  nome_r 	 TEXT NOT NULL
);

INSERT INTO regiao (sigla, nome_r) VALUES ('N', 'Norte');
INSERT INTO regiao (sigla, nome_r) VALUES ('NE', 'Nordeste');
INSERT INTO regiao (sigla, nome_r) VALUES ('CO', 'Centro-Oeste');
INSERT INTO regiao (sigla, nome_r) VALUES ('SE', 'Sudeste');
INSERT INTO regiao (sigla, nome_r) VALUES ('S', 'Sul');
```

### 2) Arquivo estados.sql

```{sql eval=FALSE, include=TRUE}
DROP TABLE IF EXISTS municipio;
DROP TABLE IF EXISTS estado;

CREATE TABLE estado(
    uf TEXT PRIMARY KEY,
    nome_e TEXT NOT NULL UNIQUE,
    regiao TEXT	  NOT NULL,
    FOREIGN KEY (regiao) REFERENCES regiao(sigla)
);

INSERT INTO estado (uf, nome_e, regiao) VALUES ('AC', 'Acre', 'N');
INSERT INTO estado (uf, nome_e, regiao) VALUES ('AL', 'Alagoas', 'NE');
INSERT INTO estado (uf, nome_e, regiao) VALUES ('AP', 'Amapá', 'N');
INSERT INTO estado (uf, nome_e, regiao) VALUES ('AM', 'Amazonas', 'N');
INSERT INTO estado (uf, nome_e, regiao) VALUES ('BA', 'Bahia', 'NE');
INSERT INTO estado (uf, nome_e, regiao) VALUES ('CE', 'Ceará', 'NE');
INSERT INTO estado (uf, nome_e, regiao) VALUES ('DF', 'Distrito Federal', 'CO');
INSERT INTO estado (uf, nome_e, regiao) VALUES ('ES', 'Espírito Santo', 'SE');
INSERT INTO estado (uf, nome_e, regiao) VALUES ('GO', 'Goiás', 'CO');
INSERT INTO estado (uf, nome_e, regiao) VALUES ('MA', 'Maranhão', 'NE');
INSERT INTO estado (uf, nome_e, regiao) VALUES ('MT', 'Mato Grosso', 'CO');
INSERT INTO estado (uf, nome_e, regiao) VALUES ('MS', 'Mato Grosso do Sul', 'CO');
INSERT INTO estado (uf, nome_e, regiao) VALUES ('MG', 'Minas Gerais', 'SE');
INSERT INTO estado (uf, nome_e, regiao) VALUES ('PA', 'Pará', 'N');
INSERT INTO estado (uf, nome_e, regiao) VALUES ('PB', 'Paraíba', 'NE');
INSERT INTO estado (uf, nome_e, regiao) VALUES ('PR', 'Paraná', 'S');
INSERT INTO estado (uf, nome_e, regiao) VALUES ('PE', 'Pernambuco', 'NE');
INSERT INTO estado (uf, nome_e, regiao) VALUES ('PI', 'Piauí', 'NE');
INSERT INTO estado (uf, nome_e, regiao) VALUES ('RJ', 'Rio de Janeiro', 'SE');
INSERT INTO estado (uf, nome_e, regiao) VALUES ('RN', 'Rio Grande do Norte', 'NE');
INSERT INTO estado (uf, nome_e, regiao) VALUES ('RS', 'Rio Grande do Sul', 'S');
INSERT INTO estado (uf, nome_e, regiao) VALUES ('RO', 'Rondônia', 'N');
INSERT INTO estado (uf, nome_e, regiao) VALUES ('RR', 'Roraima', 'N');
INSERT INTO estado (uf, nome_e, regiao) VALUES ('SC', 'Santa Catarina', 'S');
INSERT INTO estado (uf, nome_e, regiao) VALUES ('SP', 'São Paulo', 'SE');
INSERT INTO estado (uf, nome_e, regiao) VALUES ('SE', 'Sergipe', 'NE');
INSERT INTO estado (uf, nome_e, regiao) VALUES ('TO', 'Tocantins', 'N');
```

### 2) Arquivo municipios.sql (apenas o inicio do arquivo pq é grande)

```{sql eval=FALSE, include=TRUE}
DROP TABLE IF EXISTS municipio;

CREATE TABLE municipio (
  codigo INT		  PRIMARY KEY,
  nome_m 	 TEXT NOT NULL,
  uf	 TEXT	  NOT NULL,
  FOREIGN KEY (uf) REFERENCES estado(uf)
);


INSERT INTO municipio (codigo, nome_m, uf) VALUES (1100015,'Alta Floresta D''Oeste', 'RO');
INSERT INTO municipio (codigo, nome_m, uf) VALUES (1100023,'Ariquemes', 'RO');
INSERT INTO municipio (codigo, nome_m, uf) VALUES (1100031,'Cabixi', 'RO');
INSERT INTO municipio (codigo, nome_m, uf) VALUES (1100049,'Cacoal', 'RO');
INSERT INTO municipio (codigo, nome_m, uf) VALUES (1100056,'Cerejeiras', 'RO');
INSERT INTO municipio (codigo, nome_m, uf) VALUES (1100064,'Colorado do Oeste', 'RO');
INSERT INTO municipio (codigo, nome_m, uf) VALUES (1100072,'Corumbiara', 'RO');
INSERT INTO municipio (codigo, nome_m, uf) VALUES (1100080,'Costa Marques', 'RO');
INSERT INTO municipio (codigo, nome_m, uf) VALUES (1100098,'Espigão D''Oeste', 'RO');
INSERT INTO municipio (codigo, nome_m, uf) VALUES (1100106,'Guajará-Mirim', 'RO');
INSERT INTO municipio (codigo, nome_m, uf) VALUES (1100114,'Jaru', 'RO');
INSERT INTO municipio (codigo, nome_m, uf) VALUES (1100122,'Ji-Paraná', 'RO');
INSERT INTO municipio (codigo, nome_m, uf) VALUES (1100130,'Machadinho D''Oeste', 'RO');
INSERT INTO municipio (codigo, nome_m, uf) VALUES (1100148,'Nova Brasilândia D''Oeste', 'RO');
INSERT INTO municipio (codigo, nome_m, uf) VALUES (1100155,'Ouro Preto do Oeste', 'RO');
INSERT INTO municipio (codigo, nome_m, uf) VALUES (1100189,'Pimenta Bueno', 'RO');
```

### 3)

```{bash eval=FALSE, include=TRUE}

hrsdespindula@h9:~/DSBD/07-Processamento_de_Big_Data$ sqlite3 dsbd.db
-- Loading resources from /home/espinf/hrsdespindula/.sqliterc
SQLite version 3.34.1 2021-01-20 14:10:07
Enter ".help" for usage hints.
sqlite> .read regioes.sql
sqlite> .read estados.sql
sqlite> .read municipios.sql

sqlite> SELECT * FROM municipio INNER JOIN estado ON municipio.uf = estado.uf, regiao ON estado.regiao = regiao.sigla LIMIT 20;
codigo|nome_m|uf|uf|nome_e|regiao|sigla|nome_r
1100015|Alta Floresta DOeste|RO|RO|Rondônia|N|N|Norte
1100023|Ariquemes|RO|RO|Rondônia|N|N|Norte
1100031|Cabixi|RO|RO|Rondônia|N|N|Norte
1100049|Cacoal|RO|RO|Rondônia|N|N|Norte
1100056|Cerejeiras|RO|RO|Rondônia|N|N|Norte
1100064|Colorado do Oeste|RO|RO|Rondônia|N|N|Norte
1100072|Corumbiara|RO|RO|Rondônia|N|N|Norte
1100080|Costa Marques|RO|RO|Rondônia|N|N|Norte
1100098|Espigão DOeste|RO|RO|Rondônia|N|N|Norte
1100106|Guajará-Mirim|RO|RO|Rondônia|N|N|Norte
1100114|Jaru|RO|RO|Rondônia|N|N|Norte
1100122|Ji-Paraná|RO|RO|Rondônia|N|N|Norte
1100130|Machadinho DOeste|RO|RO|Rondônia|N|N|Norte
1100148|Nova Brasilândia DOeste|RO|RO|Rondônia|N|N|Norte
1100155|Ouro Preto do Oeste|RO|RO|Rondônia|N|N|Norte
1100189|Pimenta Bueno|RO|RO|Rondônia|N|N|Norte
1100205|Porto Velho|RO|RO|Rondônia|N|N|Norte
1100254|Presidente Médici|RO|RO|Rondônia|N|N|Norte
1100262|Rio Crespo|RO|RO|Rondônia|N|N|Norte
1100288|Rolim de Moura|RO|RO|Rondônia|N|N|Norte

```

### 3a

```{bash eval=FALSE, include=TRUE}
## 3A
sqlite> SELECT * FROM municipio INNER JOIN estado ON municipio.uf = estado.uf, regiao ON estado.regiao = regiao.sigla ORDER BY municipio.nome_m  LIMIT 20; 
codigo|nome_m|uf|uf|nome_e|regiao|sigla|nome_r
5200050|Abadia de Goiás|GO|GO|Goiás|CO|CO|Centro-Oeste
3100104|Abadia dos Dourados|MG|MG|Minas Gerais|SE|SE|Sudeste
5200100|Abadiânia|GO|GO|Goiás|CO|CO|Centro-Oeste
1500107|Abaetetuba|PA|PA|Pará|N|N|Norte
3100203|Abaeté|MG|MG|Minas Gerais|SE|SE|Sudeste
2300101|Abaiara|CE|CE|Ceará|NE|NE|Nordeste
2900207|Abaré|BA|BA|Bahia|NE|NE|Nordeste
4100103|Abatiá|PR|PR|Paraná|S|S|Sul
2900108|Abaíra|BA|BA|Bahia|NE|NE|Nordeste
4200051|Abdon Batista|SC|SC|Santa Catarina|S|S|Sul
1500131|Abel Figueiredo|PA|PA|Pará|N|N|Norte
4200101|Abelardo Luz|SC|SC|Santa Catarina|S|S|Sul
3100302|Abre Campo|MG|MG|Minas Gerais|SE|SE|Sudeste
2600054|Abreu e Lima|PE|PE|Pernambuco|NE|NE|Nordeste
1700251|Abreulândia|TO|TO|Tocantins|N|N|Norte
3100401|Acaiaca|MG|MG|Minas Gerais|SE|SE|Sudeste
2900306|Acajutiba|BA|BA|Bahia|NE|NE|Nordeste
2300150|Acarape|CE|CE|Ceará|NE|NE|Nordeste
2300200|Acaraú|CE|CE|Ceará|NE|NE|Nordeste
2400109|Acari|RN|RN|Rio Grande do Norte|NE|NE|Nordeste
```

### 3b

```{sql eval=FALSE, include=TRUE}
WITH tab1 as (
    SELECT * FROM municipio 
    INNER JOIN 
      estado ON municipio.uf = estado.uf, 
      regiao ON estado.regiao = regiao.sigla
) 
SELECT * FROM tab1 as t1, tab1 as t2 WHERE 
    t1.nome_m = t2.nome_m and 
    t1.codigo < t2.codigo AND 
    t1.sigla = t2.sigla 
    ORDER BY t1.nome_m LIMIT 30;
```

```{bash eval=FALSE, include=TRUE}
## 3B
sqlite> WITH tab1 as (SELECT * FROM municipio INNER JOIN estado ON municipio.uf = estado.uf, regiao ON estado.regiao = regiao.sigla) SELECT * FROM tab1 as t1, tab1 as t2 WHERE t1.nome_m = t2.nome_m and t1.codigo < t2.codigo AND t1.sigla = t2.sigla ORDER BY t1.nome_m LIMIT 30;

codigo|nome_m|uf|uf:1|nome_e|regiao|sigla|nome_r|codigo|nome_m|uf|uf:1|nome_e|regiao|sigla|nome_r
2500502|Alagoinha|PB|PB|Paraíba|NE|NE|Nordeste|2600609|Alagoinha|PE|PE|Pernambuco|NE|NE|Nordeste
2401107|Areia Branca|RN|RN|Rio Grande do Norte|NE|NE|Nordeste|2800506|Areia Branca|SE|SE|Sergipe|NE|NE|Nordeste
2401453|Baraúna|RN|RN|Rio Grande do Norte|NE|NE|Nordeste|2501534|Baraúna|PB|PB|Paraíba|NE|NE|Nordeste
2501708|Barra de São Miguel|PB|PB|Paraíba|NE|NE|Nordeste|2700607|Barra de São Miguel|AL|AL|Alagoas|NE|NE|Nordeste
4102604|Barracão|PR|PR|Paraná|S|S|Sul|4301800|Barracão|RS|RS|Rio Grande do Sul|S|S|Sul
2201507|Batalha|PI|PI|Piauí|NE|NE|Nordeste|2700706|Batalha|AL|AL|Alagoas|NE|NE|Nordeste
2501906|Belém|PB|PB|Paraíba|NE|NE|Nordeste|2700805|Belém|AL|AL|Alagoas|NE|NE|Nordeste
3107109|Boa Esperança|MG|MG|Minas Gerais|SE|SE|Sudeste|3201001|Boa Esperança|ES|ES|Espírito Santo|SE|SE|Sudeste
2102002|Bom Jardim|MA|MA|Maranhão|NE|NE|Nordeste|2602209|Bom Jardim|PE|PE|Pernambuco|NE|NE|Nordeste
2201903|Bom Jesus|PI|PI|Piauí|NE|NE|Nordeste|2401701|Bom Jesus|RN|RN|Rio Grande do Norte|NE|NE|Nordeste
2201903|Bom Jesus|PI|PI|Piauí|NE|NE|Nordeste|2502201|Bom Jesus|PB|PB|Paraíba|NE|NE|Nordeste
2401701|Bom Jesus|RN|RN|Rio Grande do Norte|NE|NE|Nordeste|2502201|Bom Jesus|PB|PB|Paraíba|NE|NE|Nordeste
4202537|Bom Jesus|SC|SC|Santa Catarina|S|S|Sul|4302303|Bom Jesus|RS|RS|Rio Grande do Sul|S|S|Sul
1501576|Bom Jesus do Tocantins|PA|PA|Pará|N|N|Norte|1703305|Bom Jesus do Tocantins|TO|TO|Tocantins|N|N|Norte
2602308|Bonito|PE|PE|Pernambuco|NE|NE|Nordeste|2904050|Bonito|BA|BA|Bahia|NE|NE|Nordeste
2401800|Brejinho|RN|RN|Rio Grande do Norte|NE|NE|Nordeste|2602506|Brejinho|PE|PE|Pernambuco|NE|NE|Nordeste
3112059|Cantagalo|MG|MG|Minas Gerais|SE|SE|Sudeste|3301108|Cantagalo|RJ|RJ|Rio de Janeiro|SE|SE|Sudeste
2701704|Capela|AL|AL|Alagoas|NE|NE|Nordeste|2801306|Capela|SE|SE|Sergipe|NE|NE|Nordeste
2402303|Caraúbas|RN|RN|Rio Grande do Norte|NE|NE|Nordeste|2504074|Caraúbas|PB|PB|Paraíba|NE|NE|Nordeste
4105003|Catanduvas|PR|PR|Paraná|S|S|Sul|4204004|Catanduvas|SC|SC|Santa Catarina|S|S|Sul
2303808|Cedro|CE|CE|Ceará|NE|NE|Nordeste|2604304|Cedro|PE|PE|Pernambuco|NE|NE|Nordeste
4105904|Colorado|PR|PR|Paraná|S|S|Sul|4305603|Colorado|RS|RS|Rio Grande do Sul|S|S|Sul
2504504|Condado|PB|PB|Paraíba|NE|NE|Nordeste|2604601|Condado|PE|PE|Pernambuco|NE|NE|Nordeste
2504603|Conde|PB|PB|Paraíba|NE|NE|Nordeste|2908606|Conde|BA|BA|Bahia|NE|NE|Nordeste
4106704|Cruzeiro do Sul|PR|PR|Paraná|S|S|Sul|4306205|Cruzeiro do Sul|RS|RS|Rio Grande do Sul|S|S|Sul
2605400|Feira Nova|PE|PE|Pernambuco|NE|NE|Nordeste|2802205|Feira Nova|SE|SE|Sergipe|NE|NE|Nordeste
4110706|Irati|PR|PR|Paraná|S|S|Sul|4207858|Irati|SC|SC|Santa Catarina|S|S|Sul
2506905|Itabaiana|PB|PB|Paraíba|NE|NE|Nordeste|2802908|Itabaiana|SE|SE|Sergipe|NE|NE|Nordeste
2607653|Itambé|PE|PE|Pernambuco|NE|NE|Nordeste|2915809|Itambé|BA|BA|Bahia|NE|NE|Nordeste
3133600|Itapeva|MG|MG|Minas Gerais|SE|SE|Sudeste|3522406|Itapeva|SP|SP|São Paulo|SE|SE|Sudeste

```

### 3c

```{sql eval=FALSE, include=TRUE}
WITH tab1 as (
    SELECT * FROM municipio 
    INNER JOIN 
      estado ON municipio.uf = estado.uf, 
      regiao ON estado.regiao = regiao.sigla
) 
SELECT DISTINCT nome_m, sigla FROM tab1 ORDER BY nome_m;
```

```{bash eval=FALSE, include=TRUE}
sqlite> WITH tab1 as (
    SELECT * FROM municipio 
    INNER JOIN 
      estado ON municipio.uf = estado.uf, 
      regiao ON estado.regiao = regiao.sigla
) 
SELECT DISTINCT nome_m, sigla FROM tab1 ORDER BY nome_m LIMIT 20;
nome_m|sigla
Abadia de Goiás|CO
Abadia dos Dourados|SE
Abadiânia|CO
Abaetetuba|N
Abaeté|SE
Abaiara|NE
Abaré|NE
Abatiá|S
Abaíra|NE
Abdon Batista|S
Abel Figueiredo|N
Abelardo Luz|S
Abre Campo|SE
Abreu e Lima|NE
Abreulândia|N
Acaiaca|SE
Acajutiba|NE
Acarape|NE
Acaraú|NE
Acari|NE
```

### 3d

```{sql eval=FALSE, include=TRUE}
WITH tab1 as (
    SELECT * FROM municipio 
    INNER JOIN 
      estado ON municipio.uf = estado.uf, 
      regiao ON estado.regiao = regiao.sigla
) 
SELECT COUNT(*) nome_m FROM tab1 WHERE sigla = 'S';
```

```{bash eval=FALSE, include=TRUE}
sqlite> WITH tab1 as (
    SELECT * FROM municipio 
    INNER JOIN 
      estado ON municipio.uf = estado.uf, 
      regiao ON estado.regiao = regiao.sigla
) 
SELECT COUNT(*) nome_m FROM tab1 WHERE sigla = 'S';
nome_m
1191

SELECT * FROM tab1 WHERE sigla = 'S' ORDER BY nome_m LIMIT 30;
codigo|nome_m|uf|uf:1|nome_e|regiao|sigla|nome_r
4100103|Abatiá|PR|PR|Paraná|S|S|Sul
4200051|Abdon Batista|SC|SC|Santa Catarina|S|S|Sul
4200101|Abelardo Luz|SC|SC|Santa Catarina|S|S|Sul
4300034|Aceguá|RS|RS|Rio Grande do Sul|S|S|Sul
4100202|Adrianópolis|PR|PR|Paraná|S|S|Sul
4200200|Agrolândia|SC|SC|Santa Catarina|S|S|Sul
4200309|Agronômica|SC|SC|Santa Catarina|S|S|Sul
4300109|Agudo|RS|RS|Rio Grande do Sul|S|S|Sul
4100301|Agudos do Sul|PR|PR|Paraná|S|S|Sul
4300208|Ajuricaba|RS|RS|Rio Grande do Sul|S|S|Sul
4300307|Alecrim|RS|RS|Rio Grande do Sul|S|S|Sul
4300406|Alegrete|RS|RS|Rio Grande do Sul|S|S|Sul
4300455|Alegria|RS|RS|Rio Grande do Sul|S|S|Sul
4200705|Alfredo Wagner|SC|SC|Santa Catarina|S|S|Sul
4100400|Almirante Tamandaré|PR|PR|Paraná|S|S|Sul
4300471|Almirante Tamandaré do Sul|RS|RS|Rio Grande do Sul|S|S|Sul
4300505|Alpestre|RS|RS|Rio Grande do Sul|S|S|Sul
4100459|Altamira do Paraná|PR|PR|Paraná|S|S|Sul
4300554|Alto Alegre|RS|RS|Rio Grande do Sul|S|S|Sul
4200754|Alto Bela Vista|SC|SC|Santa Catarina|S|S|Sul
4300570|Alto Feliz|RS|RS|Rio Grande do Sul|S|S|Sul
4100608|Alto Paraná|PR|PR|Paraná|S|S|Sul
4128625|Alto Paraíso|PR|PR|Paraná|S|S|Sul
4100707|Alto Piquiri|PR|PR|Paraná|S|S|Sul
4100509|Altônia|PR|PR|Paraná|S|S|Sul
4300604|Alvorada|RS|RS|Rio Grande do Sul|S|S|Sul
4100806|Alvorada do Sul|PR|PR|Paraná|S|S|Sul
4100905|Amaporã|PR|PR|Paraná|S|S|Sul
4300638|Amaral Ferrador|RS|RS|Rio Grande do Sul|S|S|Sul
4300646|Ametista do Sul|RS|RS|Rio Grande do Sul|S|S|Sul
```

### 3e

```{sql eval=FALSE, include=TRUE}
WITH tab1 as (
    SELECT * FROM municipio 
    INNER JOIN 
      estado ON municipio.uf = estado.uf, 
      regiao ON estado.regiao = regiao.sigla
) 
SELECT * FROM tab1 WHERE sigla = 'NE' AND nome_m LIKE '%ão%' ORDER BY nome_m;
```

```{bash eval=FALSE, include=TRUE}
SELECT * FROM tab1 WHERE sigla = 'NE' AND nome_m LIKE '%ão%' ORDER BY nome_m LIMIT 30;
codigo|nome_m|uf|uf:1|nome_e|regiao|sigla|nome_r
2500577|Algodão de Jandaíra|PB|PB|Paraíba|NE|NE|Nordeste
2100402|Altamira do Maranhão|MA|MA|Maranhão|NE|NE|Nordeste
2100436|Alto Alegre do Maranhão|MA|MA|Maranhão|NE|NE|Nordeste
2100550|Amapá do Maranhão|MA|MA|Maranhão|NE|NE|Nordeste
2100600|Amarante do Maranhão|MA|MA|Maranhão|NE|NE|Nordeste
2800100|Amparo de São Francisco|SE|SE|Sergipe|NE|NE|Nordeste
2501351|Assunção|PB|PB|Paraíba|NE|NE|Nordeste
2201051|Assunção do Piauí|PI|PI|Piauí|NE|NE|Nordeste
2501708|Barra de São Miguel|PB|PB|Paraíba|NE|NE|Nordeste
2700607|Barra de São Miguel|AL|AL|Alagoas|NE|NE|Nordeste
2101509|Barão de Grajaú|MA|MA|Maranhão|NE|NE|Nordeste
2501401|Baía da Traição|PB|PB|Paraíba|NE|NE|Nordeste
2101772|Bela Vista do Maranhão|MA|MA|Maranhão|NE|NE|Nordeste
2601607|Belém do São Francisco|PE|PE|Pernambuco|NE|NE|Nordeste
2101905|Bequimão|MA|MA|Maranhão|NE|NE|Nordeste
2502508|Boqueirão|PB|PB|Paraíba|NE|NE|Nordeste
2201945|Boqueirão do Piauí|PI|PI|Piauí|NE|NE|Nordeste
2602407|Brejão|PE|PE|Pernambuco|NE|NE|Nordeste
2503803|Caldas Brandão|PB|PB|Paraíba|NE|NE|Nordeste
2905503|Caldeirão Grande|BA|BA|Bahia|NE|NE|Nordeste
2202091|Caldeirão Grande do Piauí|PI|PI|Piauí|NE|NE|Nordeste
2603504|Camocim de São Félix|PE|PE|Pernambuco|NE|NE|Nordeste
2102556|Campestre do Maranhão|MA|MA|Maranhão|NE|NE|Nordeste
2801207|Canindé de São Francisco|SE|SE|Sergipe|NE|NE|Nordeste
2906808|Cansanção|BA|BA|Bahia|NE|NE|Nordeste
2202455|Capitão Gervásio Oliveira|PI|PI|Piauí|NE|NE|Nordeste
2202406|Capitão de Campos|PI|PI|Piauí|NE|NE|Nordeste
2801603|Cedro de São João|SE|SE|Sergipe|NE|NE|Nordeste
2103125|Central do Maranhão|MA|MA|Maranhão|NE|NE|Nordeste
2103174|Centro Novo do Maranhão|MA|MA|Maranhão|NE|NE|Nordeste

sqlite> WITH tab1 as (
    SELECT * FROM municipio 
    INNER JOIN 
      estado ON municipio.uf = estado.uf, 
      regiao ON estado.regiao = regiao.sigla
) 
SELECT COUNT(*) nome_m FROM tab1 WHERE sigla = 'NE' AND nome_m LIKE '%ão%' ORDER BY nome_m;
nome_m
241

```

